name: Main workflow
on:
  push:
    branches:
      - main  # Runs on push to main branch
  pull_request:
    branches:
      - main  # Runs on PRs targeting main branch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout  repository
        uses: actions/checkout@v4

      - name: Configure Py env
        run: |
           python -m venv .venv
           . .venv/bin/activate
           pip install -r requirements.txt
           
      - name: Add virtual environ to PATH
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Run Pyright 
        uses: jakebailey/pyright-action@v2.3.2
        with:
           warnings: true

      - name: Run tests
        run: |
           python -m unittest unitTests.py
