name: Main workflow
on:
  push:

  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout  repository
        uses: actions/checkout@v4
      
      - name: setup pyenv
        uses: "gabrielfalcao/pyenv-action@v18"
        with: 
          default: 3.8.10

      - name: Create venv for 3.8.10
        run: pyenv local 3.8.10 && python3 -mvenv .venv3810
           
      - name: Add virtual environ to PATH
        run: echo "$PWD/.venv3810/bin" >> $GITHUB_PATH

      - name: Add project requirements
        run: pip install -r requirements.txt

      - name: Run Pyright 
        uses: jakebailey/pyright-action@v2.3.2
        with:
           warnings: true

      - name: Run tests
        run: |
           python -m unittest *_test.py
           
