name: Main workflow
on:
  push:

  pull_request:

jobs:
  test:
    runs-on: ubuntu 22.04
    steps:
      - name: checkout  repository
        uses: actions/checkout@v4

      - name: Set up Python 3.8.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.10'

      - name: Configure Py env
        run: |
           python -m venv .venv
           . .venv/bin/activate
           pip install -r requirements.txt
           
      - name: Add virtual environ to PATH
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Run Pyright 
        uses: jakebailey/pyright-action@v2.3.2
        with:
           warnings: true

      - name: Run tests
        run: |
           python -m unittest *_test.py
           
